### ISSUE TITLE
Warning because bus is not copied first in network.copy()

### ISSUE THREAD

**Issue by jdedecca** [FRESNA/PyPSA#13]
Since network,copy() iterates over all_components in random order, the method raises the import_components_from_dataframe warning "The following {component} have buses which are not defined" for components which are copied before the "Bus" component is created for the network copy.
Having iterate_components() start with "Bus" would solve the issue - e.g. with a sorted dict for all_components

**Comment by nworbmot** [comment]
Hey Joao, thanks for flagging this! I've just fixed this, copying the solution from io.import_from_csv_folder(), see https://github.com/FRESNA/PyPSA/commit/4b2938056c2f54877d4f3359530d1566f51367e2. It may throw another error now because of the duplicated standard types - I'll think about how best to handle this.
