### ISSUE TITLE
ac-dc-lopf bug with Pyomo 4.4.1

### ISSUE THREAD

**Issue by jdedecca** [FRESNA/PyPSA#5]
Running the ac-dc-lopf example with Pyomo 4.4.1 yields the following error:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

The example runs correctly with Pyomo 4.3.11388.
Full output attached.

[output_pyomo4.4.1.txt](https://github.com/FRESNA/PyPSA/files/435005/output_pyomo4.4.1.txt)

**Comment by nworbmot** [comment]
I can confirm this bug. It looks like a generic problem with our hacks in pypsa.opt to make pyomo faster. I recommend downgrading Pyomo to 4.3 until we fix this, which could take some days.

Thanks for report this!

**Comment by nworbmot** [comment]
I've fixed this in the latest commit - it's due to a bad interaction between pandas and Pyomo 4.4.1. I'll make a PyPSA 0.6.1 release once I've checked there aren't any other issues with the latest versions of other libraries. Thanks for pointing this out so promptly! Quote from commit message:

Due to new code in Pyomo 4.4.1, the first index set passed to Pyomo Var or Constraint cannot be a pandas.Index - it must be converted to a list.

In

pyomo/core/base/var.py

there is a check in Var.__new__:

(args[0] == UnindexedComponent_set and len(args)==1)

If args[0] is a pandas.Index, then the first comparison will be a Boolean np.array, which cannot be combined with a single Boolean.
